---
- name: Execute authorized_key task flow
  ansible.builtin.include_tasks: ../../../_common/tasks/main.yml
  vars:
    _role_tag: "monitoring_authorized_key"
    _role_enabled: "{{ monitoring_authorized_key_enabled | default(true) | bool }}"
    _task_flow_phases_override:
      - assert
      - config
      - validate
